PACKAGE_NAME="excalibur-wmi"
PACKAGE_VERSION="2.0.0"
BUILT_MODULE_NAME[0]="excalibur"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/extra"
MAKE[0]="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/source KDIR=${kernel_source_dir} modules"
CLEAN="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/source clean"
AUTOINSTALL="yes"
